"use client";
import Image from"next/image";import{useEffect,useMemo,useState}from"react";import{AnimatePresence,motion}from"motion/react";import{Bell,Box,ChevronRight,Clipboard,Heart,Home,Moon,Plus,Search,ShoppingBag,Sun,X}from"lucide-react";import{Logo}from"./logo";import{categories,initialState,statuses,type Build,type Item,type State}from"@/lib/types";import{loadState,saveState}from"@/lib/guest-store";import{getSupabaseBrowserClient}from"@/lib/supabase/client";
type Tab="home"|"builds"|"favorites"|"prices"|"notices"|"profile";const money=(n:number)=>new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(n);const uid=()=>crypto.randomUUID();
export function GabieApp(){
 const[state,setState]=useState<State>(initialState),[ready,setReady]=useState(false),[tab,setTab]=useState<Tab>("home"),[sheet,setSheet]=useState<"build"|"item"|null>(null),[query,setQuery]=useState(""),[offers,setOffers]=useState<Offer[]>([]),[loading,setLoading]=useState(false),[searchNote,setSearchNote]=useState<string|null>(null);
 useEffect(()=>{queueMicrotask(()=>{setState(loadState());setReady(true)})},[]);useEffect(()=>{if(ready)saveState(state)},[state,ready]);const build=state.builds.find(b=>b.id===state.activeBuildId)??state.builds[0];
 const stats=useMemo(()=>{const planned=build?.items.reduce((s,i)=>s+i.planned,0)??0,spent=build?.items.reduce((s,i)=>s+i.paid,0)??0,done=build?.items.filter(i=>["Comprada","A caminho","Recebida","Instalada"].includes(i.status)).length??0;return{planned,spent,done,pct:build?.items.length?Math.round(done/build.items.length*100):0}},[build]);
 const update=(fn:(s:State)=>State)=>setState(s=>fn(structuredClone(s)));const notice=(s:State,title:string,body:string)=>s.notices.unshift({id:uid(),title,body,read:false,createdAt:new Date().toISOString()});
 function addBuild(fd:FormData){const b:Build={id:uid(),name:String(fd.get("name")),description:String(fd.get("description")||""),budget:Number(fd.get("budget")||0),items:[],createdAt:new Date().toISOString()};update(s=>{s.builds.push(b);s.activeBuildId=b.id;return s});setSheet(null);setTab("home")}
 function addItem(fd:FormData){const item:Item={id:uid(),category:String(fd.get("category")),name:String(fd.get("name")),status:"Pesquisando",priority:String(fd.get("priority")),planned:Number(fd.get("planned")||0),paid:0,owned:false,favorite:false,targetPrice:Number(fd.get("target")||0)||undefined};update(s=>{s.builds.find(b=>b.id===s.activeBuildId)?.items.push(item);return s});setSheet(null)}
 function patchItem(id:string,patch:Partial<Item>){update(s=>{const i=s.builds.flatMap(b=>b.items).find(x=>x.id===id);if(i){const old=i.status;Object.assign(i,patch);if(old!==i.status&&["Comprada","Recebida","Instalada"].includes(i.status))notice(s,`Peça marcada como ${i.status.toLowerCase()}`,i.name)}return s})}
 async function searchPrices(e:React.FormEvent){e.preventDefault();setLoading(true);setOffers([]);setSearchNote(null);try{const res=await fetch(`/api/prices?q=${encodeURIComponent(query)}`),data=await res.json(),found:Offer[]=data.results??[];setOffers(found);if(found.length===0)setSearchNote(data.notice??data.error??"Nenhuma oferta encontrada agora.");const item=build?.items.find(i=>i.name.toLowerCase().includes(query.toLowerCase())||query.toLowerCase().includes(i.name.toLowerCase()));if(item?.targetPrice&&found[0]&&found[0].price<=item.targetPrice)update(s=>{notice(s,"Preço alvo atingido! 🎉",`${item.name} apareceu por ${money(found[0].price)}.`);return s})}catch{setSearchNote("Não consegui falar com a busca agora. Tenta de novo em instantes.")}finally{setLoading(false)}}
 async function copySummary(){await navigator.clipboard.writeText(`${build.name}\n${build.items.map(i=>`• ${i.category}: ${i.name} — ${i.status} (${money(i.paid||i.planned)})`).join("\n")}\nPlanejado: ${money(stats.planned)} · Gasto: ${money(stats.spent)}`)}
 if(!ready)return <div className="grid min-h-dvh place-items-center"><Image src="/cats/cat-tired.webp" width={96} height={96} alt="Carregando" className="float rounded-full"/></div>;
 const nav=[{id:"home",label:"Início",icon:Home},{id:"builds",label:"Builds",icon:Box},{id:"favorites",label:"Favoritos",icon:Heart},{id:"prices",label:"Preços",icon:ShoppingBag},{id:"notices",label:"Avisos",icon:Bell}]as const;
 return <div className="min-h-dvh pb-24 md:pb-0 md:pl-[248px]"><header className="sticky top-0 z-30 flex h-[72px] items-center justify-between border-b border-[var(--border-soft)] bg-[var(--surface)] px-5 md:px-8"><Logo/><div className="flex items-center gap-2"><button onClick={()=>setTab("notices")} className="press relative grid size-11 place-items-center rounded-full bg-[var(--neutral)]" aria-label="Notificações"><Bell size={20}/>{state.notices.some(n=>!n.read)&&<i className="absolute right-2 top-2 size-2 rounded-full bg-[var(--primary)]"/>}</button><button onClick={()=>setTab("profile")} className="press hidden h-11 items-center gap-2 rounded-full bg-[var(--primary-soft)] px-4 text-sm font-semibold text-[var(--primary)] md:flex">G <ChevronRight size={16}/></button></div></header>
 <aside className="fixed inset-y-[72px] left-0 z-20 hidden w-[248px] flex-col border-r border-[var(--border-soft)] bg-[var(--surface)] p-4 md:flex"><p className="mb-2 px-3 text-[11px] font-bold uppercase tracking-wide text-[var(--subtle)]">Navegar</p>{nav.map(n=><Nav key={n.id}{...n} active={tab===n.id} onClick={()=>setTab(n.id)}/>)}<div className="mt-auto rounded-2xl bg-[var(--primary-soft)] p-3"><Image src="/cats/cat-happy@256.webp" width={48} height={48} alt="Gatinha feliz" className="-mt-7 rounded-full shadow-lg"/><b className="mt-2 block text-sm">Convide uma amiga</b><p className="text-xs text-[var(--muted)]">Vocês comparam builds lado a lado.</p></div></aside>
 <main className="mx-auto max-w-6xl p-5 md:p-8"><AnimatePresence mode="wait"><motion.div key={tab} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-5}} transition={{duration:.26}}>{tab==="home"&&<HomeView build={build} stats={stats} setSheet={setSheet} patchItem={patchItem} copySummary={copySummary}/>} {tab==="builds"&&<Builds state={state} setState={setState} setSheet={setSheet}/>} {tab==="favorites"&&<Items title="Favoritos" items={state.builds.flatMap(b=>b.items).filter(i=>i.favorite)} patchItem={patchItem}/>} {tab==="prices"&&<Prices query={query} setQuery={setQuery} onSubmit={searchPrices} offers={offers} loading={loading} note={searchNote}/>} {tab==="notices"&&<Notices state={state} update={update}/>} {tab==="profile"&&<Profile/>}</motion.div></AnimatePresence></main>
 <nav className="fixed inset-x-0 bottom-0 z-40 flex h-[86px] items-start justify-around rounded-t-[28px] bg-[var(--surface)] px-2 pt-2 shadow-[0_-6px_24px_-4px_rgba(159,18,57,.12)] md:hidden">{nav.map(n=><Nav key={n.id}{...n} active={tab===n.id} onClick={()=>setTab(n.id)} mobile/>)}</nav><AnimatePresence>{sheet&&<Sheet onClose={()=>setSheet(null)}>{sheet==="build"?<BuildForm onSubmit={addBuild}/>:<ItemForm onSubmit={addItem}/>}</Sheet>}</AnimatePresence></div>}
function Nav({label,icon:Icon,active,onClick,mobile}:{label:string;icon:typeof Home;active:boolean;onClick:()=>void;mobile?:boolean}){return <button onClick={onClick} className={`press ${mobile?"grid flex-1 justify-items-center gap-1 py-1 text-[10px]":"flex h-11 w-full items-center gap-3 rounded-xl px-3 text-sm"} ${active?"font-bold text-[var(--primary)]":"text-[var(--muted)]"}`}><span className={`${mobile?"grid h-7 w-12 place-items-center rounded-full":""} ${active?"bg-[var(--primary-soft)]":""}`}><Icon size={mobile?21:18}/></span>{label}</button>}
function HomeView({build,stats,setSheet,patchItem,copySummary}:{build:Build;stats:{planned:number;spent:number;done:number;pct:number};setSheet:(v:"item")=>void;patchItem:(id:string,p:Partial<Item>)=>void;copySummary:()=>void}){return <div className="grid gap-6"><section><p className="text-[var(--muted)]">Olá! Que bom te ver.</p><h1 className="text-2xl font-extrabold md:text-3xl">Vamos montar algo incrível?</h1></section><section className="rounded-[28px] bg-[var(--gradient)] p-5 text-white shadow-[0_8px_20px_-3px_rgba(225,29,72,.3)] md:p-7"><p className="text-[11px] font-bold uppercase tracking-wider opacity-75">Build atual</p><div className="mt-1 flex items-center justify-between"><h2 className="text-xl font-bold">{build.name}</h2><span className="brand text-3xl">{stats.pct}%</span></div><div className="mt-4 h-2.5 overflow-hidden rounded-full bg-white/25"><motion.i initial={{width:0}} animate={{width:`${stats.pct}%`}} transition={{duration:.42}} className="block h-full rounded-full bg-white"/></div><div className="mt-4 grid grid-cols-3 gap-2 rounded-[18px] bg-white/15 p-3 text-sm"><div><small className="opacity-70">Peças</small><b className="block">{stats.done}/{build.items.length}</b></div><div><small className="opacity-70">Planejado</small><b className="block">{money(stats.planned)}</b></div><div><small className="opacity-70">Disponível</small><b className="block">{money(build.budget-stats.spent)}</b></div></div></section><div className="flex items-center justify-between"><h2 className="text-lg font-bold">Suas peças</h2><div className="flex gap-1"><button onClick={copySummary} className="press grid size-11 place-items-center rounded-full bg-[var(--neutral)]" aria-label="Copiar resumo"><Clipboard size={18}/></button><button onClick={()=>setSheet("item")} className="press flex h-11 items-center gap-2 rounded-full bg-[var(--primary)] px-4 text-sm font-bold text-white"><Plus size={18}/>Peça</button></div></div><Items items={build.items} patchItem={patchItem}/></div>}
function Items({title,items,patchItem}:{title?:string;items:Item[];patchItem:(id:string,p:Partial<Item>)=>void}){return <section>{title&&<h1 className="mb-5 text-2xl font-extrabold">{title}</h1>}<div className="grid gap-3">{items.length?items.map(i=><article key={i.id} className="card press flex items-center gap-3 p-3"><div className="grid size-12 shrink-0 place-items-center rounded-[15px] bg-[var(--primary-soft)] text-[var(--primary)]"><Box size={21}/></div><div className="min-w-0 flex-1"><b className="block truncate">{i.name}</b><p className="truncate text-xs text-[var(--subtle)]">{i.category} · {i.priority} · alvo {money(i.planned)}</p></div><button onClick={()=>patchItem(i.id,{favorite:!i.favorite})} className="grid size-11 place-items-center" aria-label="Favoritar"><Heart size={20} className={i.favorite?"fill-[var(--primary)] text-[var(--primary)]":"text-[var(--subtle)]"}/></button><select aria-label={`Status de ${i.name}`} value={i.status} onChange={e=>patchItem(i.id,{status:e.target.value})} className="hidden max-w-32 rounded-full border border-[var(--border)] bg-[var(--neutral)] px-3 py-2 text-xs font-bold sm:block">{statuses.map(s=><option key={s}>{s}</option>)}</select></article>):<div className="card grid justify-items-center gap-2 p-8 text-center"><Image src="/cats/cat-sleeping@256.webp" width={96} height={96} alt="Gatinha dormindo" className="float rounded-full"/><b>Nada por aqui ainda</b><p className="text-sm text-[var(--muted)]">Quando você adicionar peças, elas aparecem aqui.</p></div>}</div></section>}
function Builds({state,setState,setSheet}:{state:State;setState:React.Dispatch<React.SetStateAction<State>>;setSheet:(v:"build")=>void}){return <div><div className="mb-5 flex items-center justify-between"><div><h1 className="text-2xl font-extrabold">Minhas builds</h1><p className="text-sm text-[var(--muted)]">{state.builds.length} projeto(s) neste dispositivo</p></div><button onClick={()=>setSheet("build")} className="press flex h-11 items-center gap-2 rounded-full bg-[var(--primary)] px-4 font-bold text-white"><Plus size={18}/>Nova</button></div><div className="grid gap-4 sm:grid-cols-2">{state.builds.map(b=><button key={b.id} onClick={()=>setState(s=>({...s,activeBuildId:b.id}))} className={`card press p-5 text-left ${state.activeBuildId===b.id?"ring-2 ring-[var(--primary)]":""}`}><div className="flex justify-between"><b className="text-lg">{b.name}</b><span className="rounded-full bg-[var(--primary-soft)] px-3 py-1 text-[11px] font-bold uppercase text-[var(--primary)]">{state.activeBuildId===b.id?"Atual":"Abrir"}</span></div><p className="mt-1 text-sm text-[var(--muted)]">{b.description||"Sua próxima máquina."}</p><p className="mt-4 text-sm"><b>{b.items.length}</b> peças · orçamento {money(b.budget)}</p></button>)}</div></div>}
type Offer={title:string;store:string;price:number;condition:string;url:string};function Prices({query,setQuery,onSubmit,offers,loading,note}:{query:string;setQuery:(v:string)=>void;onSubmit:(e:React.FormEvent)=>void;offers:Offer[];loading:boolean;note:string|null}){return <div><h1 className="text-2xl font-extrabold">Comparar preços</h1><p className="mb-5 text-sm text-[var(--muted)]">Busca manual; cada consulta atualiza seu histórico.</p><form onSubmit={onSubmit} className="relative"><Search className="absolute left-4 top-3.5 text-[var(--subtle)]" size={20}/><input value={query} onChange={e=>setQuery(e.target.value)} required minLength={3} placeholder="Ex.: ASUS Prime RTX 5070" className="h-12 w-full rounded-full border border-[var(--border)] bg-[var(--surface)] pl-12 pr-28 outline-none"/><button className="press absolute right-1 top-1 h-10 rounded-full bg-[var(--primary)] px-5 font-bold text-white" disabled={loading}>{loading?"Buscando…":"Buscar"}</button></form>{note&&!loading&&<div className="card mt-5 flex items-center gap-4 p-5"><Image src="/cats/cat-sad@256.webp" width={64} height={64} alt="" aria-hidden className="size-16 shrink-0 rounded-full object-cover"/><p className="text-sm text-[var(--muted)]">{note}</p></div>}<div className="mt-5 grid gap-3">{offers.map((o,i)=><a href={o.url} target="_blank" rel="noreferrer sponsored" key={o.url} className={`card press flex items-center gap-3 p-4 ${i===0?"border-[var(--primary)] bg-[var(--primary-soft)]":""}`}><span className="grid size-10 place-items-center rounded-xl bg-[var(--neutral)] font-bold">{o.store?.[0]||"L"}</span><div className="min-w-0 flex-1"><b className="line-clamp-1">{o.title}</b><small className="text-[var(--muted)]">{o.store} · {o.condition}</small></div><strong className="text-lg">{money(o.price)}</strong><ChevronRight size={18}/></a>)}</div></div>}
function Notices({state,update}:{state:State;update:(fn:(s:State)=>State)=>void}){return <div><div className="mb-5 flex items-center justify-between"><h1 className="text-2xl font-extrabold">Avisos</h1><button onClick={()=>update(s=>{s.notices.forEach(n=>n.read=true);return s})} className="text-sm font-bold text-[var(--primary)]">Marcar como lidos</button></div><div className="grid gap-3">{state.notices.map(n=><article key={n.id} className={`card flex gap-3 p-4 ${!n.read?"border-[var(--primary)] bg-[var(--primary-soft)]":""}`}><span className="grid size-11 shrink-0 place-items-center rounded-[14px] bg-[var(--surface)] text-[var(--primary)]"><Bell size={19}/></span><div><b>{n.title}</b><p className="text-sm text-[var(--muted)]">{n.body}</p></div></article>)}</div></div>}
function Profile(){
 const[dark,setDark]=useState(false),[email,setEmail]=useState<string|null>(null),[authBusy,setAuthBusy]=useState(false),[authError,setAuthError]=useState<string|null>(null);
 const supabase=useMemo(()=>getSupabaseBrowserClient(),[]);
 useEffect(()=>{queueMicrotask(()=>setDark(document.documentElement.dataset.theme==="dark"))},[]);
 useEffect(()=>{if(!supabase)return;let alive=true;
  supabase.auth.getUser().then(({data})=>{if(alive)setEmail(data.user?.email??null)});
  const{data:sub}=supabase.auth.onAuthStateChange((_event,session)=>setEmail(session?.user?.email??null));
  return()=>{alive=false;sub.subscription.unsubscribe()}},[supabase]);
 function toggle(){const next=!dark;setDark(next);document.documentElement.dataset.theme=next?"dark":"light";localStorage.setItem("gw-theme",next?"dark":"light")}
 async function signIn(){if(!supabase)return;setAuthBusy(true);setAuthError(null);
  const{error}=await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:`${location.origin}/auth/callback`}});
  // On success the browser navigates away, so we only land here when it failed.
  if(error){setAuthBusy(false);setAuthError("Login com Google ainda não está liberado nesta conta do Supabase.")}}
 async function signOut(){if(!supabase)return;setAuthBusy(true);await supabase.auth.signOut();setEmail(null);setAuthBusy(false)}
 return <div className="mx-auto max-w-xl"><h1 className="text-2xl font-extrabold">Perfil e ajustes</h1><div className="card mt-5 p-5"><div className="flex items-center gap-4"><Image src="/cats/cat-curious@256.webp" width={72} height={72} alt="Gatinha curiosa" className="rounded-full shadow-lg"/><div className="min-w-0"><b className="text-lg">{email?"Conta conectada":"Modo convidado"}</b><p className="truncate text-sm text-[var(--muted)]">{email??"Os dados ficam somente neste navegador."}</p></div></div>
 <button onClick={toggle} className="press mt-5 flex h-12 w-full items-center justify-between rounded-2xl bg-[var(--neutral)] px-4"><span className="flex items-center gap-2">{dark?<Moon size={19}/>:<Sun size={19}/>}Tema {dark?"escuro":"claro"}</span><span className="text-sm text-[var(--muted)]">Alternar</span></button>
 {!supabase
  ? <button disabled className="mt-3 h-12 w-full rounded-2xl bg-[var(--primary)] font-bold text-white opacity-70">Entrar com Google · em configuração</button>
  : email
   ? <button onClick={signOut} disabled={authBusy} className="press mt-3 h-12 w-full rounded-2xl border border-[var(--border)] font-bold disabled:opacity-60">{authBusy?"Saindo…":"Sair da conta"}</button>
   : <button onClick={signIn} disabled={authBusy} className="press mt-3 h-12 w-full rounded-2xl bg-[var(--primary)] font-bold text-white disabled:opacity-70">{authBusy?"Abrindo o Google…":"Entrar com Google"}</button>}
 {authError&&<p className="mt-3 text-sm text-[var(--primary)]">{authError}</p>}
 </div></div>}
function Sheet({children,onClose}:{children:React.ReactNode;onClose:()=>void}){return <motion.div initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-50 bg-black/40 backdrop-blur-sm" onMouseDown={onClose}><motion.div initial={{y:"100%"}} animate={{y:0}} exit={{y:"100%"}} transition={{duration:.32,ease:[.2,.8,.3,1]}} onMouseDown={e=>e.stopPropagation()} className="absolute inset-x-0 bottom-0 max-h-[90dvh] overflow-auto rounded-t-[28px] bg-[var(--surface)] p-5 md:inset-y-0 md:left-auto md:w-[420px] md:rounded-none"><div className="mx-auto mb-4 h-1 w-12 rounded-full bg-[var(--border)] md:hidden"/><button onClick={onClose} className="absolute right-4 top-4 grid size-10 place-items-center rounded-full bg-[var(--neutral)]" aria-label="Fechar"><X size={18}/></button>{children}</motion.div></motion.div>}
const Field=({label,...props}:{label:string;name:string;[key:string]:unknown})=><label className="grid gap-1.5 text-sm font-semibold">{label}<input {...props} className="h-12 rounded-[14px] border border-[var(--border)] bg-[var(--surface)] px-4 font-normal outline-none"/></label>;
function BuildForm({onSubmit}:{onSubmit:(f:FormData)=>void}){return <form action={onSubmit} className="grid gap-4 pt-8"><h2 className="text-xl font-bold">Nova build</h2><Field name="name" label="Nome" required placeholder="Meu setup dos sonhos"/><Field name="description" label="Descrição" placeholder="O que você quer montar?"/><Field name="budget" type="number" min="0" step="0.01" label="Orçamento total" placeholder="8000"/><button className="press mt-2 h-12 rounded-full bg-[var(--primary)] font-bold text-white">Criar build</button></form>}
function ItemForm({onSubmit}:{onSubmit:(f:FormData)=>void}){return <form action={onSubmit} className="grid gap-4 pt-8"><h2 className="text-xl font-bold">Adicionar peça</h2><Field name="name" label="Produto" required placeholder="Ex.: RTX 5070 ASUS Prime"/><label className="grid gap-1.5 text-sm font-semibold">Categoria<select name="category" className="h-12 rounded-[14px] border border-[var(--border)] bg-[var(--surface)] px-4">{categories.map(c=><option key={c}>{c}</option>)}</select></label><label className="grid gap-1.5 text-sm font-semibold">Prioridade<select name="priority" className="h-12 rounded-[14px] border border-[var(--border)] bg-[var(--surface)] px-4">{["Essencial","Importante","Upgrade","Opcional"].map(c=><option key={c}>{c}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><Field name="planned" type="number" min="0" step="0.01" label="Preço esperado"/><Field name="target" type="number" min="0" step="0.01" label="Preço alvo"/></div><button className="press mt-2 h-12 rounded-full bg-[var(--primary)] font-bold text-white">Adicionar</button></form>}
